name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "rewrite" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry==1.8.2
        poetry install --with=dev
    - name: Run pre-commit
      env:
        SKIP: pytest
      run: |
        poetry run pre-commit run --all-files --show-diff-on-failure --color=always
    - name: Test with pytest
      run: poetry run pytest
